from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from typing import List, Optional, Union, Dict, Any
from fastapi import HTTPException, status
from sqlalchemy.exc import IntegrityError
from uuid import UUID # Import UUID

from app.models.flywheel import Flywheel
from app.schemas.flywheel import (
    FlywheelCreate, FlywheelUpdate
)

class CRUDFlywheel:
    def __init__(self, db: AsyncSession):
        self.db = db

    async def create(self, *, obj_in: FlywheelCreate) -> Flywheel:
        """Creates a new Flywheel for a specific user."""
        # user_id and other fields come from FlywheelCreate
        # id is generated by default in the model
        data = obj_in.model_dump()
        db_obj = Flywheel(**data)
        self.db.add(db_obj)
        try:
            await self.db.commit()
            await self.db.refresh(db_obj)
            return db_obj
        except IntegrityError as e:
            await self.db.rollback()
            # Duplicate primary key error is less likely now with UUID default,
            # but could happen if UUID generation collides (extremely rare)
            # or if an ID *was* somehow provided and already exists.
            if 'flywheel_pkey' in str(e.orig):
                raise HTTPException(
                    status_code=status.HTTP_409_CONFLICT,
                    detail=f"Failed to create flywheel due to potential ID conflict."
                )
            # Check for foreign key violation (user_id not found)
            elif 'flywheel_user_id_fkey' in str(e.orig):
                 raise HTTPException(
                    status_code=status.HTTP_404_NOT_FOUND, # Or 400 Bad Request
                    detail=f"User with ID '{obj_in.user_id}' not found."
                )
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Could not create Flywheel due to data integrity issue: {e.orig}"
            )

    async def get(self, *, id: UUID, user_id: UUID) -> Optional[Flywheel]:
        """Retrieves a single Flywheel by its ID and User ID."""
        result = await self.db.execute(
            select(Flywheel).filter(Flywheel.id == id, Flywheel.user_id == user_id)
        )
        return result.scalars().first()

    async def get_multi_by_user(
        self, *, user_id: UUID, skip: int = 0, limit: int = 100
    ) -> List[Flywheel]:
        """Retrieves multiple Flywheels for a specific user."""
        query = select(Flywheel).filter(Flywheel.user_id == user_id)
        query = query.order_by(Flywheel.created_at.desc()) # Optional: order by creation date
        query = query.offset(skip).limit(limit)
        result = await self.db.execute(query)
        return result.scalars().all()

    async def update(
        self, *, db_obj: Flywheel, obj_in: Union[FlywheelUpdate, Dict[str, Any]]
    ) -> Flywheel:
        """Updates an existing Flywheel.
        Assumes db_obj was already verified to belong to the correct user.
        """
        if isinstance(obj_in, dict):
            update_data = obj_in
        else:
            update_data = obj_in.model_dump(exclude_unset=True)

        # Ensure user_id is not being updated if present in update_data dict
        update_data.pop('user_id', None)
        # id is not updatable and not in FlywheelUpdate schema
        # update_data.pop('id', None)

        for field, value in update_data.items():
            setattr(db_obj, field, value)

        self.db.add(db_obj)
        try:
            await self.db.commit()
            await self.db.refresh(db_obj)
            return db_obj
        except IntegrityError as e:
            await self.db.rollback()
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Could not update Flywheel due to data integrity issue: {e.orig}"
            )

    async def remove(self, *, id: UUID, user_id: UUID) -> Optional[Flywheel]:
        """Deletes a Flywheel by its ID and User ID."""
        # First, get the object ensuring it belongs to the user
        db_obj = await self.get(id=id, user_id=user_id)
        if db_obj:
            await self.db.delete(db_obj)
            try:
                await self.db.commit()
                return db_obj
            except IntegrityError as e:
                await self.db.rollback()
                raise HTTPException(
                    status_code=status.HTTP_409_CONFLICT,
                    detail=f"Cannot delete Flywheel due to constraints: {e.orig}"
                )
        # If get didn't find it for this user, return None (or raise 404 in API layer)
        return None

# --- Optional Test Functions --- (Update to include user_id)
import os
import asyncio
from uuid import uuid4 # Import uuid4
from app.database.database import AsyncSessionLocal
from app.schemas.flywheel import FlywheelCreate, FlywheelUpdate

async def test_crud_flywheel(db: AsyncSession, user_id: UUID):
    print(f"\n🧪 Testing CRUDFlywheel for user {user_id}...")
    crud = CRUDFlywheel(db)
    created_id: Optional[UUID] = None # To store the ID of the created flywheel

    # --- Create ---
    create_data = FlywheelCreate(
        user_id=user_id,
        name="Test Business Flywheel",
        description="A flywheel for testing purposes.",
        edges=[
            {"id": "t1", "text": "Acquire Users"},
            {"id": "t2", "text": "Engage Users"}
        ],
        image_path="/images/test.jpg" # Renamed image_url to image_path
    )
    try:
        created = await crud.create(obj_in=create_data)
        assert created.id is not None
        assert isinstance(created.id, UUID)
        assert created.image_path == "/images/test.jpg"
        created_id = created.id # Store the generated ID
        print(f"✅ Created: {created.id} with image_path: {created.image_path}") # Updated print
    except HTTPException as e:
        print(f"❌ Error creating: {e.detail}")
        pytest.fail(f"CRUD create failed: {e.detail}")
        return

    # --- Get ---
    fetched = await crud.get(id=created_id, user_id=user_id)
    assert fetched is not None
    assert fetched.id == created_id
    assert fetched.user_id == user_id
    assert fetched.name == "Test Business Flywheel"
    assert fetched.image_path == "/images/test.jpg"
    print(f"✅ Fetched: {fetched.id}")

    # --- Get Multi By User ---
    multi = await crud.get_multi_by_user(user_id=user_id)
    assert any(fw.id == created_id for fw in multi)
    # Check if image_path is present in fetched multi items if needed
    print(f"✅ Multi fetch count for user: {len(multi)}")

    # --- Update ---
    update_data = FlywheelUpdate(
        description="An updated description.",
        image_path="/images/updated.png" # Renamed image_url to image_path
    )
    try:
        updated = await crud.update(db_obj=fetched, obj_in=update_data)
        assert updated.id == created_id
        assert updated.description == "An updated description."
        assert updated.image_path == "/images/updated.png"
        print(f"✅ Updated: {updated.id} with image_path: {updated.image_path}") # Updated print
    except HTTPException as e:
        print(f"❌ Error updating: {e.detail}")
        pytest.fail(f"CRUD update failed: {e.detail}")

    # --- Update image_path to None ---
    update_none_data = FlywheelUpdate(image_path=None) # Renamed image_url to image_path
    try:
        updated_none = await crud.update(db_obj=updated, obj_in=update_none_data)
        assert updated_none.image_path is None
        print(f"✅ Set image_path to None for ID: {updated_none.id}") # Updated print
    except HTTPException as e:
        print(f"❌ Error setting image_path to None: {e.detail}") # Updated print
        pytest.fail(f"CRUD update to None failed: {e.detail}")

    # --- Remove ---
    try:
        removed = await crud.remove(id=created_id, user_id=user_id)
        assert removed is not None
        assert removed.id == created_id
        print(f"✅ Removed: {removed.id}")
    except HTTPException as e:
        print(f"❌ Error removing: {e.detail}")
        pytest.fail(f"CRUD remove failed: {e.detail}")

    # --- Verify removal --- 
    fetched_after_remove = await crud.get(id=created_id, user_id=user_id)
    assert fetched_after_remove is None
    print(f"✅ Verified removal for {created_id} for user {user_id}")

    # --- Test Cleanup (Optional but good practice) ---
    # Ensure the item is actually deleted if tests failed mid-way
    # This requires a separate session potentially
    # print(f"🧹 Final cleanup check for {created_id}")
    # async with AsyncSessionLocal() as cleanup_session:
    #     crud_cleanup = CRUDFlywheel(cleanup_session)
    #     obj = await crud_cleanup.get(id=created_id, user_id=user_id)
    #     if obj:
    #         print(f"    Found leftover object, attempting delete...")
    #         await crud_cleanup.remove(id=created_id, user_id=user_id)
    #         print(f"    Cleanup delete attempted.")


# --- Main execution part remains similar --- 
async def main():
    # Load environment variables if needed (e.g., for database URL)
    from dotenv import load_dotenv
    load_dotenv()
    test_user_id_str = os.getenv("TEST_USER_ID")
    if not test_user_id_str:
        print("❌ Error: TEST_USER_ID environment variable not set.")
        return
    try:
        test_user_id = UUID(test_user_id_str.strip())
    except ValueError:
        print(f"❌ Error: Invalid UUID format for TEST_USER_ID: {test_user_id_str}")
        return

    async with AsyncSessionLocal() as session:
        await test_crud_flywheel(session, test_user_id) # Pass user_id to test function
    print("\n🏁 All Flywheel CRUD tests completed.")

if __name__ == "__main__":
    import pytest # Import pytest for fail
    try:
        asyncio.run(main())
    except RuntimeError as e:
        if "Cannot run the event loop while another loop is running" in str(e):
            print("Note: Test script seems to be running within an existing event loop.")
        else:
            raise e 